title: DST Wuzzy The Buzzy
description: Wiki for DST mod Wuzzy The Buzzy
markdown: kramdown 
remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme
show_downloads: false
github:
  is_project_page: false
